resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final


# 3421
# 3312
# 3263
# 3262
# 3363
# 1079 - windows
#


resources:
- name: r-stemcell-v3421
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells
    product_version: 3421\..*

- name: r-stemcell-v1079-windows
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells-windows-server
    product_version: 1079\..*

- name: stemcell-pipeline
  type: git
  source:
    uri: {{stemcell_pipeline_git_uri}}
    branch: master
    private_key: {{git_private_key}}

- name: pcf-pipelines
  type: git
  source:
    uri: {{pcf_pipelines_git_uri}}
    branch: master
    private_key: {{git_private_key}}

- name: schedule
  type: time
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM

jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true

  - get: pcf-pipelines
  - get: stemcell-pipeline

  - get: stemcell-v3421
    resource: r-stemcell-v3421
    params:
      globs:
      - {{iaas_type_glob}}

  - get: stemcell-v1079-windows
    resource: r-stemcell-v1079-windows
    params:
      globs:
      - {{iaas_type_glob}}

- name: upload-latest-stemcells
  plan:
  - get: pcf-pipelines
    passed:
    - regulator
    trigger: true
  - get: stemcell-v3421
    resource: r-stemcell-v3421
    params:
      globs:
      - {{iaas_type_glob}}

  - get: stemcell-v1079-windows
    resource: r-stemcell-v1079-windows
    params:
      globs:
      - {{iaas_type_glob}}

  - task: wait-opsman-clear
    file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}

  - task: upload-stemcell-v3421
    file: stemcell-pipeline/tasks/upload-stemcells/task.yml
    input_mapping:
      stemcells: stemcell-v3421
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}

  - task: upload-stemcell-v1079-windows
    file: stemcell-pipeline/tasks/upload-stemcells/task.yml
    input_mapping:
      stemcells: stemcell-v1079-windows
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}